### ISSUE TITLE
Can't Commit - Permission Denied to ad479

### ISSUE THREAD

**Issue by ad479** [selfcommit/HospiPal#1]
Hi Dan,

I tried to create a branch off of Master for my dev repo but received the following message:

remote: Permission to selfcommit/HospiPal.git denied to ad479.
fatal: unable to access 'https://github.com/selfcommit/HospiPal.git/': The reque
sted URL returned error: 403

Do you want to give me credentials to commit?

Best regards.
Bobby

**Comment by selfcommit** [comment]
Hi Bobby,
I'd like to have you Fork the repo, creating your own repository.  
That way we can generate pull requests back and forth, without directly committing on top of each others code.
Let me know if you need a hand with this.
